title: TREC Product Search and Recommendations Track
email: rikiya.takehi@fuji.waseda.jp
description: >-
  Advancing multimodal retrieval and recommendation methods for online product discovery experiences

# Base settings
baseurl: ""  # Blank for local testing
url: "https://rikiyat.github.io"  # Your GitHub Pages domain

twitter_username: rikiya_takehi
github_username:  RikiyaT 

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

kramdown:
  parse_block_html: true

markdown: CommonMarkGhPages

commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
